### PR TITLE
Issue#93

### PR DESCRIPTION
**Pull request by Pontusfroding**
fix for #93 

Now all template namespaces have been added and I can add people if I don't use pagesets. There seems to be some issue there.

Class 'pager' not found in php/traits/showPage.inc.php on line 72

### CODE REVIEW

**Comment by jeroenrnl** [comment]
I think I have created a fix for the "Class pager" issue recently... Have you checked with the "hotfix" branch?

**Comment by Pontusfroding** [comment]
Can't see anything about it being fixed in there unfortunately.

Is anybody using the pagesets? :)

**Comment by jeroenrnl** [comment]
Great, thanks!
Two small requests: could you use ```use template\template``` instead of adding the namespace to the call? And also, in templates I use <?= ?> instead of <?php echo ?>
I'd be happy to change it, BTW, but I'm still figuring out how to pull a commit into a different branch then "master" :-)

**Comment by jeroenrnl** [comment]
I will also look into the showPage issue...

**Comment by jeroenrnl** [comment]
I have reproduced it on my system

**Comment by jeroenrnl** [comment]
Ok, the pager issue is fixed (see 22fb768) and I have found a way to pull your changes into my issue#93 branch. Do you want to make the fixes above or should I do it?

**Comment by Pontusfroding** [comment]
You are always free to do what fits you best with my patches.

Anyway I have now updated the branch.

**Pull request merged**
